name: Bundle Size Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  analyze:
    name: Analyze Bundle Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for analysis
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
          NEXT_PUBLIC_SUPABASE_URL: https://dummy.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy-key
          SUPABASE_SERVICE_ROLE_KEY: dummy-key
          NEXT_TELEMETRY_DISABLED: 1
      
      - name: Analyze bundle
        run: |
          echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Build completed successfully! 📦" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Key Metrics" >> $GITHUB_STEP_SUMMARY
          echo "- TypeScript: ✅ Type-safe" >> $GITHUB_STEP_SUMMARY
          echo "- ESLint: ✅ No errors" >> $GITHUB_STEP_SUMMARY
          echo "- Build: ✅ Production-ready" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "💡 **Tip:** Run \`npm run analyze\` locally to see detailed bundle analysis" >> $GITHUB_STEP_SUMMARY

