name: Validate Dependencies

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  validate-lockfile:
    name: Validate package-lock.json
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      
      - name: Verify lock file integrity
        run: |
          echo "🔍 Verifying package-lock.json is in sync with package.json..."
          npm ci
          echo "✅ Lock file is valid and in sync!"
        
      - name: Check for vulnerabilities
        run: |
          echo "🔒 Checking for security vulnerabilities..."
          npm audit --audit-level=moderate || true
          echo "✅ Security check complete!"
      
      - name: Comment on PR (if validation fails)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Dependency validation failed!**\n\n' +
                    'The `package-lock.json` file is out of sync with `package.json`.\n\n' +
                    '**To fix this:**\n' +
                    '```bash\n' +
                    'npm install\n' +
                    'git add package-lock.json\n' +
                    'git commit -m "chore: update package-lock.json"\n' +
                    'git push\n' +
                    '```\n\n' +
                    'See [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#dependency-management) for more details.'
            })

